#### Custom configuration for Fluentd
kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd
  namespace: logging
data:
  fluent.conf: |-
    <source>
      @type forward
      port 24224
    </source>
    <filter **>
      @type stdout
    </filter>
    <match **>
       @type s3
       s3_bucket ltvco-challenge
       s3_region us-east-1
       aws_key_id AKIATAV4OCR7NO
       aws_sec_key itVsKIoxQ9Oaio/a2gkiBXog6sr
       s3_object_key_format "${tag}/%{time_slice}-events_%{index}.%{file_extension}"
       time_slice_format %Y/%m/%d/%H
       time_slice_wait 10m
       path test-logs
       # if you want to use ${tag} or %Y/%m/%d/ like syntax in path / s3_object_key_format,
       # need to specify tag for ${tag} and time for %Y/%m/%d in <buffer> argument.
       <buffer tag,time>
         @type file
         flush_mode interval
         flush_interval 30s
         path /var/log/fluent/s3
         timekey 300 # 1 hour partition
         timekey_wait 1m
         timekey_use_utc true # use utc
         chunk_limit_size 100m
       </buffer>
       <format>
         @type json
       </format>
    </match>
---
#### Fluentd Kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  namespace: logging
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: djfoley01/fluentd-s3:latest
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc
      volumes:
      - name: config-volume
        configMap:
          name: fluentd
---
#### Fluentd Kubernetes Service
apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: logging
spec:
  ports:
  - port: 24224
    protocol: TCP
  selector:
    app: fluentd
  type: ClusterIP
