apiVersion: v1
kind: Service
metadata:
  name: {{ include "sb.fullname" . }}
  labels:
    {{- include "sb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: https
  selector:
    {{- include "sb.selectorLabels" . | nindent 4 }}
